
[     UTC     ] Logs for deltavision.streamlit.app/
────────────────────────────────────────────────────────────────────────────────────────
[17:14:44] 🚀 Starting up repository: 'deltavision', branch: 'main', main module: 'streamlit_app.py'
[17:14:44] 🐙 Cloning repository...
[17:14:45] 🐙 Cloning into '/mount/src/deltavision'...

[17:14:45] 🐙 Cloned repository!
[17:14:45] 🐙 Pulling code changes from Github...
[17:14:45] 📦 Processing dependencies...
Prepared 62 packages in 1m 30s
Installed 62 packages in 1.01s
 + annotated-doc==0.0.3
 + annotated-types==0.7.0
 + anyio==4.11.0
 + click==8.3.0
 + contourpy==1.3.3
 + cycler==0.12.1
 + fastapi==0.120.1
 + filelock==3.20.0
 + fonttools==4.60.1
 + fsspec==2025.9.0
 + h11==0.16.0
 + httptools==0.7.1
 + idna==3.11
 + imageio==2.37.0
 + jinja2==3.1.6
 +[2025-10-29 17:16:17.326064]  kiwisolver==1.4.9
 + lazy-loader==0.4
 + markupsafe==3.0.3
 + matplotlib==3.10.7
 + mpmath==1.3.0
 + networkx==3.5
 +[2025-10-29 17:16:17.326322]  numpy==2.3.4
 + nvidia-cublas-cu12==12.8.4.1
 + nvidia-cuda-cupti-cu12==12.8.90
 + nvidia-cuda-nvrtc-cu12==12.8.93
 + nvidia-cuda-runtime-cu12==12.8.90
 +[2025-10-29 17:16:17.326545]  nvidia-cudnn-cu12==9.10.2.21
 + nvidia-cufft-cu12==11.3.3.83
 + nvidia-cufile-cu12==1.13.1.3
 + nvidia-curand-cu12==10.3.9.90
 + nvidia-cusolver-cu12==11.7.3.90
 [2025-10-29 17:16:17.326779] + nvidia-cusparse-cu12==12.5.8.93
 + nvidia-cusparselt-cu12==0.7.1
 + nvidia-nccl-cu12==2.27.5
 + nvidia-nvjitlink-cu12==12.8.93
 + nvidia-nvshmem-cu12==3.3.20[2025-10-29 17:16:17.326949] 
 + nvidia-nvtx-cu12==12.8.90
 + opencv-python==4.11.0.86
 + packaging==25.0
 + pillow==12.0.0
 + pydantic==[2025-10-29 17:16:17.327069] 2.12.3
 + pydantic-core==2.41.4
 + pyparsing==3.2.5
 + python-dateutil==2.9.0.post0
 + python-dotenv==1.2.1
 [2025-10-29 17:16:17.327245] + pyyaml==6.0.3
 + scikit-image==0.25.2
 + scipy==1.16.3
 + setuptools==80.9.0
 + six[2025-10-29 17:16:17.327366] ==1.17.0
 + sniffio==1.3.1
 + starlette==0.49.1
 + sympy==1.14.0
 + tifffile==2025.10.16[2025-10-29 17:16:17.327494] 
 + torch==2.9.0
 + triton==3.5.0
 + typing-extensions==4.15.0
 + typing-inspection==0.4.2
 + [2025-10-29 17:16:17.327611] uvicorn==0.38.0
 + uvloop==0.22.1
 + watchfiles==1.1.1
 + websockets==15.0.1
[17:16:18] 🐍 Python dependencies were installed from /mount/src/deltavision/uv.lock using uv-sync.
[17:16:18] 📦 WARN: More than one requirements file detected in the repository. Available options: uv-sync /mount/src/deltavision/uv.lock, uv /mount/src/deltavision/requirements.txt, poetry /mount/src/deltavision/pyproject.toml. Used: uv-sync with /mount/src/deltavision/uv.lock
Check if streamlit is installed

──────────────────────────────── Installing Streamlit ──────────────────────────────────

Using uv pip install.
Using Python 3.13.9 environment at /home/adminuser/venv
Resolved 37 packages in 505ms
Prepared 27 packages in 1.41s
Installed 27 packages in 72ms
 + altair==5.5.0
 + attrs==25.4.0
 + blinker==1.9.0
 + cachetools==6.2.1
 + certifi==2025.10.5
 + charset-normalizer==3.4.4
 + gitdb==4.0.12
 + gitpython==3.1.45
 + jsonschema==4.25.1
 + jsonschema-specifications==[2025-10-29 17:16:20.393545] 2025.9.1
 + narwhals==2.10.0
 + pandas==2.3.3
 + protobuf==6.33.0
 + pyarrow==21.0.0
 + pydeck==0.9.1
 + pytz==2025.2
 + referencing==0.37.0
 + requests==2.32.5
 [2025-10-29 17:16:20.393727] + rpds-py==0.28.0
 + smmap==5.0.2
 + streamlit==1.51.0
 + tenacity==9.1.2
 + toml==0.10.2
 + tornado==6.5.2
 + tzdata==2025.2[2025-10-29 17:16:20.393884] 
 + urllib3==2.5.0
 + watchdog==6.0.0

────────────────────────────────────────────────────────────────────────────────────────

[17:16:20] 📦 Processed dependencies!
[17:16:23] ❗️ The service has encountered an error while checking the health of the Streamlit app: Get "http://localhost:8501/healthz": dial tcp 127.0.0.1:8501: connect: connection refused



2025-10-29 17:16:31.712 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 129, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/deltavision/streamlit_app.py", line 5, in <module>
    from src.image_processing import align_images, load_image, resize_image
  File "/mount/src/deltavision/src/image_processing.py", line 1, in <module>
    import cv2
  File "/home/adminuser/venv/lib/python3.13/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
    ~~~~~~~~~^^
  File "/home/adminuser/venv/lib/python3.13/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
[17:17:14] 🐙 Pulling code changes from Github...
[17:17:15] 📦 Processing dependencies...
[17:17:15] 📦 Processed dependencies!
[17:17:16] 🔄 Updated app!
2025-10-29 17:18:24.668 Uncaught app execution
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 129, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/deltavision/streamlit_app.py", line 5, in <module>
    from src.image_processing import align_images, load_image, resize_image
  File "/mount/src/deltavision/src/image_processing.py", line 1, in <module>
    import cv2
ImportError: libGL.so.1: cannot open shared object file: No such file or directory